### ISSUE TITLE
SECTION 1.1. USER LOG IN FORM

### ISSUE THREAD

**Issue by kcp3000** [WasteWiseACK/Waste-Wise#16]
***Following "Swiss" Web design;***
**Task:** Implement a log in form that allows users to log into their accounts.

**Users should be able to log into their accounts with their username and passwords securely.**

**Requirements**
* The form must include:
- [ ] Input value with "username" (required)
- [ ] Input value with "password" (required)
- [ ] Button able to submit username and password
* Others
- [ ] h1 tag for welcoming statement
- [ ] If any of the information is incorrect or missing, error message appears

![Image](https://github.com/user-attachments/assets/df9c6390-1084-4a93-8ee5-dac585a1a2cf)
