### ISSUE TITLE
SECTION 2.2. FUNCTIONALITY OF "JOIN THE CAUSE"

### ISSUE THREAD

**Issue by kcp3000** [WasteWiseACK/Waste-Wise#18]
**Task:** Implement navigation functionality using React Router to handle the page change. Clicking on the "JOIN THE CAUSE" link should navigate to the Sign Up page.

**Users should be able to click on 'JOIN THE CAUSE' and be directed to the sign up page so that they can create an account.**

**Requirements:**
- [ ] Create a route for the sign up page
- [ ] Make sure users will be taken to the correct route when clicking on the link
- [ ] Make sure the sign up form is the default form rendered upon users being directly routed

![Image](https://github.com/user-attachments/assets/a0d76655-f0dc-477c-92e5-8994d94b1dd4)
