### ISSUE TITLE
SECTION 4.1. FORM FOR BOROUGHS

### ISSUE THREAD

**Issue by kcp3000** [WasteWiseACK/Waste-Wise#23]
**TASK** Create a form that allows users to filter food banks based on their borough

Users should be able to filter through our food bank information to find banks in specific boroughs

**Requirements:**
- [x] Design a filter form that includes a dropdown for borough selection (Bronx, Manhattan, Queens, Brooklyn, Staten Island)
- [x] Use useState to manage the selected borough
- [x] Fetch and display food banks based on the selected borough![Image](https://github.com/user-attachments/assets/5ce8b978-2e54-4132-b87c-b29dc8cfb445)
