### ISSUE TITLE
SECTION 1. BUTTON COMPONENT FOR SWITCHING BETWEEN SIGN-UP AND LOG IN

### ISSUE THREAD

**Issue by cindynguyen0917** [WasteWiseACK/Waste-Wise#34]
**Task:** Implement a button component that allows Users to switch between the form that allows them to create an account or log into their account depending on the page they are viewing. The UI should switch seamlessly without needing to refresh the page.

**Users should be able to toggle between the Sign up and Log in forms in order to fit their needs**

Requirements:
*Technical:
- [ ] Create the HTML for the button
- [ ] Use React Hooks (UseState) to manage toggling between the forms
- [ ] Use conditional state to update the form based on the state
- [ ] The text of the button is dynamic and changes depending on the state

* Others:
- [ ] The button is visible on both the sign up ('Already a user?') and log in ('Need an account')  form 
- [ ] Clicking on the button successfully switches between forms without the page reloading
![Image](https://github.com/user-attachments/assets/8e07bf90-7479-4c20-8f54-6a65ca26748e)
![Image](https://github.com/user-attachments/assets/e0961cfa-47b4-4d2e-ae1e-489887b561a5)
