### ISSUE TITLE
SECTION 5. DEVELOP FILTERING SECTION ON FORUM PAGE

### ISSUE THREAD

**Issue by cindynguyen0917** [WasteWiseACK/Waste-Wise#35]
**Task:** Create a filtering UI component that allows users to filter posts based on tags

Users should be view posts on the forum and be able to filter them based of specific criteria to find discussions they are interested in

**Requirements:**
- [ ] Create a form for the filtering section using checkboxes
- [ ] Connect that form to interact with our Post API database by using the correct information for queries
- [ ] The correct posts are being displayed upon filtering
- [ ] Add a reset functionality to show all the posts again

![Image](https://github.com/user-attachments/assets/06ba3f9a-81db-481d-a401-b604cbe84565)
