### ISSUE TITLE
SECTION 3. NAVIGATION BAR

### ISSUE THREAD

**Issue by cindynguyen0917** [WasteWiseACK/Waste-Wise#7]
***Following "Swiss" Web design;***
**Task:** Create a navigation bar for the website

**Users should be able to easily navigate and access different sections of the site including, the CO2 and food insecurity map, local food banks, why we care, solutions, and forum page.**

**Requirements**

- [ ] Create links for Home, Why We Care (with dropdown for Impact, Solutions, Food Banks), Forum
- [ ] Uses semantic tags
- [ ] `<nav>` should include `<ul> `which will hold `<li>` for each navigation path
- [ ] Add a profile image `<img>` wrapped in an `<a>` tag that allows users to click on the photo as a link to their profile or sign in page
- [ ] Implement dropdown functionality for 'Why We Care': Dropdown menu should include Impact, Solutions, and Food Banks
- [ ] Drop down feature will require that 'Why We Care' is a `<ul>` with each drop down being a `<li>`
- [ ] Test navigation links: Ensure each link directs the user to the correct section/page
- [ ] The navigation bar is consistent and is applied all throughout the application
- [ ]  Ensure the navigation bar is accessible (screen reader compatibility, mobile, etc.)

![Image](https://github.com/user-attachments/assets/518adcef-72e9-446f-9560-a31fcbadacbc)
